interface end0
{
  AdvSendAdvert on;
  AdvDefaultLifetime 0;
  prefix ::/64
  {
    AdvOnLink on;
    AdvAutonomous on;
    AdvRouterAddr off;
    AdvValidLifetime infinity;
    AdvPreferredLifetime infinity;
  };
};
