# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-vit-fpga"
BBFILE_PATTERN_meta-vit-fpga = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-vit-fpga = "7"

LAYERDEPENDS_meta-vit-fpga = "petalinux networking-layer"
LAYERSERIES_COMPAT_meta-vit-fpga = "scarthgap"
