#!/usr/bin/env bash
set -e

#MISE description="Save Vivado project to a .tcl script"

#USAGE flag "-l --log" {
#USAGE  arg <file>
#USAGE  help "Path to place a log file (relative to vivado/project) [default: no logging]"
#USAGE }
#USAGE flag "-j --journal" {
#USAGE  arg <file>
#USAGE  help "Path to place a journal file (relative to vivado/project) [default: no journaling]"
#USAGE }

if [[ -z $usage_log ]]; then LOG="-nolog"; else LOG="-log $usage_log"; fi
if [[ -z $usage_journal ]]; then JOU="-nojournal"; else JOU="-journal $usage_journal"; fi

cd vivado/project
vivado -mode batch "$LOG" "$JOU" "$(find -- *.xpr)" -source ../scripts/save.tcl -tclargs ../scripts/create.tcl
